name: Update GUI screenshots

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  documentation:
    uses: ./.github/workflows/documentation.yml
    with:
      source_ref: ${{ github.sha }}
      refresh_screenshots: true
